### ISSUE TITLE
Criar botão para ir para a tela do detalhe do prestador 500pts - Time Flávia

### ISSUE THREAD

**Issue by evandrojr** [raciocinio-computacional/PsicHelp#30]
Isso já é feito acontece ao clicar em um item da listagem, entretanto algumas pessoas não percebem que existe mais uma tela depois.

Vamos colocar um botão com o texto [mais] no mesmo nível do preço, mas colado do lado direito. Basta colocar o desenho do botão que eu acho que já vai funcionar.

#FICAADICA

Arquivo a ser alterado:
https://github.com/raciocinio-computacional/PsicHelp/blob/master/src/pages/locais/locais.html

Botões:
https://ionicframework.com/docs/api/components/button/Button/

**Comment by flaviandradde** [comment]
Professor tem algum link explicando como fazer isso?
Em 09/07/2018 12:18, "Evandro Magalhães Leite Júnior" <
notifications@github.com> escreveu:
